### ISSUE TITLE
Class 'Tohur\SocialConnect\ApplicationException' not found

### ISSUE THREAD

**Issue by chrisvidal** [TohurTV/oc-socialconnect-plugin#7]
thanks for the latest version of the plugin. I am in the midst of testing and so far I found some issues.
I can't test anything actually since I am not using the new Twitch API and I do not need it, but the plugin is expecting anyway a with API key in the pluging.php method `registerSchedule` which breaks everything.

```php
Class 'Tohur\SocialConnect\ApplicationException' not found in /var/www/html/eclia/plugins/tohur/socialconnect/Plugin.php:84
```

**Comment by tohurtv** [comment]
I must have forgot to put the use call in the top will fix. update will be out by the end of the night

**Comment by tohurtv** [comment]
also sorry for the delays in response but notifications from github aren't working for me atm

**Comment by tohurtv** [comment]
Update should be pushing out now. its in the build que on Octobers side of things

**Comment by tohurtv** [comment]
Is this still causing issues since I updated it? needing to know as I can proceed to separate these functions into another plugin if so. main reason I have everything api wise in this as trying to limit the amount of plugins people need to install use some my other plugins as alot of the services I use in them have social logins and so made sense to  put most the core api stuff in this. If I need to separate these into another plugin I will
